### ISSUE TITLE
Composer failed to install wasa/client-php-sdk

### ISSUE THREAD

**Issue by Lathanao** [wasakredit/magento-2-extension#5]
Hello,

I'm trying to install this Magento extension.
The extension works well in BO.
Not in FO.

The composer.json require "wasa/client-php-sdk": "v3.0".

I think doing: composer require wasakredit/php-checkout-sdk
should works fine, but not.

Composer doesn't find any package of this name. I tried:
wasakredit/php-checkout-sdk
wasa/php-checkout-sdk
wasakredit/client-php-sdk
etc...

No one looks exist.

Please, what is right way to install this library?

**Comment by kahrewk** [comment]
Hello,

The intended way to install this library is to download the latest build from the [releases page](https://github.com/wasakredit/magento-2-extension/releases) extract this to the root of your magento installation and follow the [installation instructions](https://github.com/wasakredit/magento-2-extension#installation) in order to enable the plugin.

**Comment by Lathanao** [comment]
Ah ok, I see the repo:
 "url": "https://github.com/wasakredit/php-checkout-sdk.git"
 
 I will try this way.

**Comment by Lathanao** [comment]
I really need to get a clean Composer install, so here what I did:

With this CLI, I can record a repo:
composer config repositories.secret '{"type": "vcs","url": "https://github.com/wasakredit/php-checkout-sdk.git"}'

Fail with:
composer require wasa/php-checkout-sdk

Succeed with :
composer require wasa/client-php-sdk

On FO, I get this error:
require_once(/var/www/XXXXXXX/vendor/wasa/php-checkout-sdk/Wasa.php): failed to open stream: etc....

It's the first time I do that with composer. But I wonder if the name in this file is well set or not:
https://github.com/wasakredit/php-checkout-sdk/blob/master/composer.json

Is the name should not be "wasa/php-checkout-sdk" ?

**Comment by Lathanao** [comment]
No need anymore to fix anything.
Thank for the extension.
